### ISSUE TITLE
Use `corr` instead of `cov` in the GaussianMultivariate

### ISSUE THREAD

**Issue by csala** [sdv-dev/Copulas#191]
On its definition, a Gaussian Copula is based on a correlation matrix that should be made of values in the range [-1, 1].
In our `GaussianMultivariate` implementation we are computing the correlation matrix by actually using the `cov` function on the matrix of marginal cdfs inverted using a standard normal inverse cdf. So, the covariance that we end up obtaining is actually the covariance of that matrix instead of the correlation. On the paper, both matrices should be equivalent because the theoretical distribution of the random values used to compute them is standard normal. However, in practice, if the sample size is not big enough and the std deviates from 1, they end up being quite different, which may result in an incorrect correlation matrix, made of values outside of the expected range.

https://github.com/sdv-dev/Copulas/blob/99c3032be61c0523432acc26d964aa317e8cfdd7/copulas/multivariate/gaussian.py#L73-L74

Should we change `cov` to `corr`?

**Comment by rollervan** [comment]
Here's a short analysis of the `cov` vs `corr`:

We generate a multivariate distribution with a `gamma`, `beta` and `uniform`distributions, and analyze the resulting covariance matrix. 
```python
a = 5
alpha, bet = 0.4, 0.9
loc, scale = 0, 1

xv = gamma(a)
yv = beta(alpha, bet)
zv = uniform(loc, scale)
x = np.expand_dims(xv.rvs(size=n_samples),-1)
y = np.expand_dims(yv.rvs(size=n_samples),-1)
z = np.expand_dims(zv.rvs(size=n_samples),-1)

data = np.concatenate([x,y,z],-1)
columns = ['x', 'y', 'z']
data = pd.DataFrame(data, columns=columns)

gammauni = GammaUnivariate()
betauni = BetaUnivariate()
unifuni = UniformUnivariate()
dist_cov = GaussianMultivariate(distribution={
    "x": gammauni,
    "y": betauni,
    "z": unifuni})
dist.fit(data)
```

Once fitted, their covariance matrices (dist.covariance) look as:

    Resulting Covariance Matrix using cov
    [[ 1.02059415 -0.14296247  0.26275174]
     [-0.14296247  1.60603163  0.03584365]
     [ 0.26275174  0.03584365  1.9122526 ]]
    
    Resulting Covariance Matrix using corr
    [[ 1.         -0.11166536  0.18808165]
     [-0.11166536  1.          0.02045326]
     [ 0.18808165  0.02045326  1.        ]]

Theoretically, the resulting covariance matrix must be equivalent to the correlation matrix. In fact, the frobenius norm of their differences decrease with the number of samples:

![output_1_0](https://user-images.githubusercontent.com/17121671/93632188-eafe7780-f9ba-11ea-8f29-893521a0171a.png)

The discrepancies in such matrices due to the sample size can provoke substantial differences for some distributions, as the uniform:


![output_8_1](https://user-images.githubusercontent.com/17121671/93632874-12a20f80-f9bc-11ea-9638-82a169c337d7.png)
